version: "2"
services:
  node:
    image: "node:15"
    user: "node"
    working_dir: /home/node/metrika72
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    volumes:
      - ./:/home/node/metrika72
    ports:
      - "3000:3000"
#    expose:
#      - "8081"
    command: "npm start"
